language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: aAbZ6kQBWEPTM9dzmjK2IDHEaB/IUYzG1e5z7mLSM7iq8goki9T65kE9rZNg+RH2hXgr104HWzF6tRltP0rz+S+l/Wj0KpImZ8G622Zb2OVpa9fGx6dbY2ke3Z0U9R2hpJm+v0KzQYeR25agZ9Wc54m49KlgguQswU/lzl65KA8khEfE+DsBG1G2dE4x5vcU5GsB3k3/iCFcY+1qoMQIWPKvorfBmy9cwMikFrCaKvi+6Sr2Hc7m6dXmAvMg3ljiFksE0PsoCOq+yd9lIbqbJ2YWneArQXLQT30YRHs8psUgz4JFqH3ntb5ujC6LffSDZPMMEZuAyRJzp9HmLTHkyszIl2Vcj70W7bADjMEmLgrsuXtxVgmCD8JJi/P5v1xYZp4qzdNb9e6O5jelpE0iTtbbYd9etBjGdmH5PcGcd8OVXh1d5V3R3E8YRR1ca9JMIoGPj9DrNVEOOruWzpc5EzLzrAa95iHj/VaIlyZ1E3QBxykhbWAlYFDIIOoiqESV00UYM2fvxmfd3hwqpsROxi1a5rb+MMlBwHE/8nOcUnhzMNk1GiiFIAAqm/p75OUI2eAwboH111ND0+06aOUUW9BPBSsBhB1Icq2exIBH3Wy5Lg/gEqvDkIAriGRdnlnNVhrnlq9+R2WmcN8swhWvwQt0VkdEsuWi2tivlNZs46E=
  - secure: RVbFOyYRl3NWyfolsBt3euQhk+B+MfvjmdOvzAS9nysF09bT4MgaVBoDurXhUebHnlhbK3VqBJ2a9Dvbzp9H0plvukA0PpG3ceYNHLNeRRgMddKjBxIncFjIP3/DxZKu58JnHKGCXwWt6cOY828VHnwTWrm1RTj7HkFlF1QCoFdHYSjHnUrHaQeSsDx/2lzAWToOxFjekclEBIr7ourrBhO6aeR/TdZP0ZhEHtcPGCyhkxxCleFZfWwA4gHcEPla3U7oJ5fUcHq/GUSb55K4n1de0jBiEF5o652NO0nsI/rkJUcp4GbTvocRf7yCgvUxhzMGS55bn3kPXkNS3GJ+Kd8cHMOLmofTbx8wWoVa6egIh0ADgKcgS0QNcjtisW4fB4PgVPhXkN4yKla/g7DyR3eOaXd3RrfJD+BYK6mEzgg3hwyvKc4fJX4H+GTKrq8MHpHo1wdP5GzFWafXnnM8R0Z2K9tS+ySqottWesMn89ZHkFmkanQnfCT+1p2MiOBiKM6QzNBzHezNBNi9laaQIMnUu80n0b2m173nE7qulp/jC4xsQvY0r3sMwnENyG30zFcMmrBmefAR+H/zJjuG3GAY8psfU/fJ43eRdeTXC9SEDBn/y0w3z9RTCPCqEEgKtl9AXZwv+VHTV2at1T0UXs7QFzgFD1zIhc94P4Je3+s=
  - secure: OCgsCJI/87E8y/OmXC41WbTv+qHO0jnbzax1NWxskQS3Pb0V4VDECqhC6wU8fWtzbDvIZDGe+fSEgWmAlUCCDCxzgsg6wZSVqdVEqh0SSXfYAUz0Cra6oMKT32pIcWmMNthSUOCOM+WjETaqDal0rb7I/SoXOGghcINlu/bSOg9zjDX62T/mgAlAe+5wlsovZCX1B06ecm56qSr7PpJIfngePr1wV4GTRUnScSXH1erHrJamDls/SA1ImfBLAd+iLRoarYq42nqBK9qc/jSjkwy1D1HKfBS+8qWx/iv7/WZQzw3oC37D44t4PgGZPO7+YwQa2DMasEc1EMT+03tNK51uCFK7c6cIx2D/rfEk6DxEaQ4aKiFoVMS49W86A2BEPZ1rhB5BMXWbcYJcZI9SwiAC7pv8MMV4QtRDxfIU80aUp9IK9UWbihbBe1iH8WdNLswkEVZXIvwADdWQGoHPnA54fGMxG13/v4f/matflTgEBvwkFB+U7rkTg3bQdGwRn//6T+xgu8HBx0vzSeX8Cr4VHHiUnnAu4lvlAQ8PHgVdK0+0AkltncS9n3dC3zl3K5XsCLeFni3LVxobEvVgyC0Qs960VlfFtZs/WTL1blsRDvV3ALRvCZ2/WskxTlV0rJ3mHcfVMq3AxD/QUbVeneW7tKJd93sWjgo8bT4chdw=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
